/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        primary:        '#10B981',
        primaryHover:   '#059669',
        primaryText:    '#FFFFFF',
        actionReset:    '#FC686F',
        actionInfo:     '#5D87FF',
        actionDiscount: '#F863A2',
        actionDraft:    '#FBB018',
        inStock:        '#10B981',
        outOfStock:     '#EF4444',
        discountBadge:  '#10B981',
        paidRow:        '#10B981',
        dueRow:         '#EF4444',
        totalRow:       '#1F2937',
        statusCell:     '#F3F4F6',
        white:          '#FFFFFF',
        pageBg:         '#F5F6FA',
        cardBg:         '#FFFFFF',
        inputBg:        '#FFFFFF',
        borderLight:    '#E5E7EB',
        borderMedium:   '#D1D5DB',
        textPrimary:    '#111827',
        textSecondary:  '#6B7280',
        textMuted:      '#9CA3AF',
        navBg:          '#FFFFFF',
        navBorder:      '#E5E7EB',
        navTimeColor:   '#10B981',
      },
      fontFamily: {
        sans: ['Nunito', 'system-ui', '-apple-system', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
