import { DataSource } from 'typeorm';
import { Medicine } from '../../modules/medicines/entities/medicine.entity';

const dataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '5432', 10),
  username: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASS || 'admin123',
  database: process.env.DB_NAME || 'pharma-pos-dev',
  entities: [Medicine],
  synchronize: false,
  ssl:
    process.env.NODE_ENV === 'production'
      ? { rejectUnauthorized: false }
      : false,
});

const medicines = [
  {
    name: 'Paracetamol 500mg',
    genericName: 'Acetaminophen',
    barcode: '8901234567890',
    brand: 'Cipla',
    category: 'Pain Relief',
    unit: 'Pcs',
    price: 2.5,
    discountPct: 0,
    stock: 1000,
  },
  {
    name: 'Ibuprofen 400mg',
    genericName: 'Ibuprofen',
    barcode: '8901234567891',
    brand: 'GSK',
    category: 'Pain Relief',
    unit: 'Pcs',
    price: 3.0,
    discountPct: 5,
    stock: 800,
  },
  {
    name: 'Amoxicillin 500mg',
    genericName: 'Amoxicillin',
    barcode: '8901234567892',
    brand: 'Sun Pharma',
    category: 'Antibiotic',
    unit: 'Pcs',
    price: 8.5,
    discountPct: 0,
    stock: 500,
  },
  {
    name: 'Cetirizine 10mg',
    genericName: 'Cetirizine',
    barcode: '8901234567893',
    brand: 'Mankind',
    category: 'Allergy',
    unit: 'Pcs',
    price: 4.0,
    discountPct: 10,
    stock: 1200,
  },
  {
    name: 'Metformin 500mg',
    genericName: 'Metformin HCl',
    barcode: '8901234567894',
    brand: 'USV',
    category: 'Diabetes',
    unit: 'Pcs',
    price: 6.0,
    discountPct: 0,
    stock: 750,
  },
  {
    name: 'Amlodipine 5mg',
    genericName: 'Amlodipine Besylate',
    barcode: '8901234567895',
    brand: 'Abbott',
    category: 'Cardiovascular',
    unit: 'Pcs',
    price: 12.0,
    discountPct: 0,
    stock: 600,
  },
  {
    name: 'Omeprazole 20mg',
    genericName: 'Omeprazole',
    barcode: '8901234567896',
    brand: 'Dr. Reddy',
    category: 'Gastrointestinal',
    unit: 'Pcs',
    price: 15.0,
    discountPct: 8,
    stock: 450,
  },
  {
    name: 'Azithromycin 250mg',
    genericName: 'Azithromycin',
    barcode: '8901234567897',
    brand: 'Pfizer',
    category: 'Antibiotic',
    unit: 'Pcs',
    price: 45.0,
    discountPct: 0,
    stock: 300,
  },
  {
    name: 'Vitamin C 500mg',
    genericName: 'Ascorbic Acid',
    barcode: '8901234567898',
    brand: 'Himalaya',
    category: 'Vitamins',
    unit: 'Pcs',
    price: 5.0,
    discountPct: 15,
    stock: 2000,
  },
  {
    name: 'Dolo 650',
    genericName: 'Paracetamol',
    barcode: '8901234567899',
    brand: 'Micro Labs',
    category: 'Pain Relief',
    unit: 'Pcs',
    price: 3.5,
    discountPct: 0,
    stock: 1500,
  },
  {
    name: 'Montelukast 10mg',
    genericName: 'Montelukast Sodium',
    barcode: '8901234567900',
    brand: 'Cipla',
    category: 'Respiratory',
    unit: 'Pcs',
    price: 28.0,
    discountPct: 0,
    stock: 400,
  },
  {
    name: 'Pantoprazole 40mg',
    genericName: 'Pantoprazole Sodium',
    barcode: '8901234567901',
    brand: 'Alkem',
    category: 'Gastrointestinal',
    unit: 'Pcs',
    price: 35.0,
    discountPct: 12,
    stock: 350,
  },
  {
    name: 'Atorvastatin 20mg',
    genericName: 'Atorvastatin Calcium',
    barcode: '8901234567902',
    brand: 'Lupin',
    category: 'Cardiovascular',
    unit: 'Pcs',
    price: 25.0,
    discountPct: 0,
    stock: 500,
  },
  {
    name: 'Levocetirizine 5mg',
    genericName: 'Levocetirizine Dihydrochloride',
    barcode: '8901234567903',
    brand: 'Mankind',
    category: 'Allergy',
    unit: 'Pcs',
    price: 18.0,
    discountPct: 5,
    stock: 600,
  },
  {
    name: 'Aceclofenac 100mg',
    genericName: 'Aceclofenac',
    barcode: '8901234567904',
    brand: 'Zydus',
    category: 'Pain Relief',
    unit: 'Pcs',
    price: 22.0,
    discountPct: 0,
    stock: 400,
  },
  {
    name: 'Metronidazole 400mg',
    genericName: 'Metronidazole',
    barcode: '8901234567905',
    brand: 'Sun Pharma',
    category: 'Antibiotic',
    unit: 'Pcs',
    price: 8.0,
    discountPct: 0,
    stock: 550,
  },
  {
    name: 'ORS Powder',
    genericName: 'Oral Rehydration Salt',
    barcode: '8901234567906',
    brand: 'WHO',
    category: 'Electrolytes',
    unit: 'Pcs',
    price: 15.0,
    discountPct: 0,
    stock: 800,
  },
  {
    name: 'Furosemide 40mg',
    genericName: 'Furosemide',
    barcode: '8901234567907',
    brand: 'Sanofi',
    category: 'Diuretic',
    unit: 'Pcs',
    price: 10.0,
    discountPct: 0,
    stock: 300,
  },
  {
    name: 'Aspirin 75mg',
    genericName: 'Acetylsalicylic Acid',
    barcode: '8901234567908',
    brand: 'Bayer',
    category: 'Cardiovascular',
    unit: 'Pcs',
    price: 5.0,
    discountPct: 0,
    stock: 700,
  },
  {
    name: 'Ranitidine 150mg',
    genericName: 'Ranitidine HCl',
    barcode: '8901234567909',
    brand: 'GSK',
    category: 'Gastrointestinal',
    unit: 'Pcs',
    price: 12.0,
    discountPct: 0,
    stock: 450,
  },
  {
    name: 'Multivitamin',
    genericName: 'Vitamin Complex',
    barcode: '8901234567910',
    brand: 'Centrum',
    category: 'Vitamins',
    unit: 'Pcs',
    price: 85.0,
    discountPct: 10,
    stock: 200,
  },
  {
    name: 'Calcium Carbonate 500mg',
    genericName: 'Calcium Carbonate',
    barcode: '8901234567911',
    brand: 'Dr. Reddy',
    category: 'Supplements',
    unit: 'Pcs',
    price: 8.0,
    discountPct: 0,
    stock: 900,
  },
  {
    name: 'Ferrous Sulfate',
    genericName: 'Iron Supplement',
    barcode: '8901234567912',
    brand: 'Mankind',
    category: 'Supplements',
    unit: 'Pcs',
    price: 15.0,
    discountPct: 0,
    stock: 400,
  },
  {
    name: 'Thyroxine 50mcg',
    genericName: 'Levothyroxine Sodium',
    barcode: '8901234567913',
    brand: 'Abbott',
    category: 'Thyroid',
    unit: 'Pcs',
    price: 35.0,
    discountPct: 0,
    stock: 350,
  },
  {
    name: 'Gliclazide 80mg',
    genericName: 'Gliclazide',
    barcode: '8901234567914',
    brand: 'USV',
    category: 'Diabetes',
    unit: 'Pcs',
    price: 28.0,
    discountPct: 0,
    stock: 400,
  },
  {
    name: 'Losartan 50mg',
    genericName: 'Losartan Potassium',
    barcode: '8901234567915',
    brand: 'Cipla',
    category: 'Cardiovascular',
    unit: 'Pcs',
    price: 45.0,
    discountPct: 8,
    stock: 500,
  },
  {
    name: 'Clindamycin 300mg',
    genericName: 'Clindamycin HCl',
    barcode: '8901234567916',
    brand: 'Pfizer',
    category: 'Antibiotic',
    unit: 'Pcs',
    price: 180.0,
    discountPct: 0,
    stock: 150,
  },
  {
    name: 'Doxycycline 100mg',
    genericName: 'Doxycycline Hyclate',
    barcode: '8901234567917',
    brand: 'Sun Pharma',
    category: 'Antibiotic',
    unit: 'Pcs',
    price: 25.0,
    discountPct: 0,
    stock: 400,
  },
  {
    name: 'Ondansetron 4mg',
    genericName: 'Ondansetron HCl',
    barcode: '8901234567918',
    brand: 'Zydus',
    category: 'Antiemetic',
    unit: 'Pcs',
    price: 35.0,
    discountPct: 0,
    stock: 300,
  },
  {
    name: 'Domperidone 10mg',
    genericName: 'Domperidone',
    barcode: '8901234567919',
    brand: 'Mankind',
    category: 'Antiemetic',
    unit: 'Pcs',
    price: 15.0,
    discountPct: 0,
    stock: 500,
  },
  {
    name: 'Salbutamol 2mg',
    genericName: 'Salbutamol Sulfate',
    barcode: '8901234567920',
    brand: 'Cipla',
    category: 'Respiratory',
    unit: 'Pcs',
    price: 8.0,
    discountPct: 0,
    stock: 600,
  },
  {
    name: 'Bromhexine 8mg',
    genericName: 'Bromhexine HCl',
    barcode: '8901234567921',
    brand: 'Mankind',
    category: 'Respiratory',
    unit: 'Pcs',
    price: 12.0,
    discountPct: 0,
    stock: 450,
  },
  {
    name: 'Cetamol 500mg',
    genericName: 'Paracetamol',
    barcode: '8901234567922',
    brand: 'GSK',
    category: 'Pain Relief',
    unit: 'Pcs',
    price: 2.0,
    discountPct: 0,
    stock: 2000,
  },
  {
    name: 'Norfloxacin 400mg',
    genericName: 'Norfloxacin',
    barcode: '8901234567923',
    brand: 'Dr. Reddy',
    category: 'Antibiotic',
    unit: 'Pcs',
    price: 22.0,
    discountPct: 0,
    stock: 350,
  },
  {
    name: 'Ciprofloxacin 500mg',
    genericName: 'Ciprofloxacin HCl',
    barcode: '8901234567924',
    brand: 'Sun Pharma',
    category: 'Antibiotic',
    unit: 'Pcs',
    price: 35.0,
    discountPct: 0,
    stock: 400,
  },
  {
    name: 'Acyclovir 400mg',
    genericName: 'Acyclovir',
    barcode: '8901234567925',
    brand: 'Zydus',
    category: 'Antiviral',
    unit: 'Pcs',
    price: 120.0,
    discountPct: 0,
    stock: 200,
  },
  {
    name: 'Albendazole 400mg',
    genericName: 'Albendazole',
    barcode: '8901234567926',
    brand: 'Mankind',
    category: 'Anthelmintic',
    unit: 'Pcs',
    price: 18.0,
    discountPct: 0,
    stock: 500,
  },
  {
    name: 'Mebendazole 100mg',
    genericName: 'Mebendazole',
    barcode: '8901234567927',
    brand: 'GSK',
    category: 'Anthelmintic',
    unit: 'Pcs',
    price: 25.0,
    discountPct: 0,
    stock: 400,
  },
  {
    name: 'Loperamide 2mg',
    genericName: 'Loperamide HCl',
    barcode: '8901234567928',
    brand: 'Abbott',
    category: 'Antidiarrheal',
    unit: 'Pcs',
    price: 15.0,
    discountPct: 0,
    stock: 350,
  },
  {
    name: 'Secnidazole 1g',
    genericName: 'Secnidazole',
    barcode: '8901234567929',
    brand: 'Pfizer',
    category: 'Antiprotozoal',
    unit: 'Pcs',
    price: 45.0,
    discountPct: 0,
    stock: 250,
  },
  {
    name: 'Hydrochlorothiazide 25mg',
    genericName: 'Hydrochlorothiazide',
    barcode: '8901234567930',
    brand: 'Lupin',
    category: 'Diuretic',
    unit: 'Pcs',
    price: 8.0,
    discountPct: 0,
    stock: 400,
  },
  {
    name: 'Spironolactone 25mg',
    genericName: 'Spironolactone',
    barcode: '8901234567931',
    brand: 'Sanofi',
    category: 'Diuretic',
    unit: 'Pcs',
    price: 35.0,
    discountPct: 0,
    stock: 300,
  },
  {
    name: 'Prednisolone 10mg',
    genericName: 'Prednisolone',
    barcode: '8901234567932',
    brand: 'Abbott',
    category: 'Corticosteroid',
    unit: 'Pcs',
    price: 25.0,
    discountPct: 0,
    stock: 450,
  },
  {
    name: 'Betamethasone Cream',
    genericName: 'Betamethasone Valerate',
    barcode: '8901234567933',
    brand: 'GSK',
    category: 'Dermatological',
    unit: 'Pcs',
    price: 85.0,
    discountPct: 5,
    stock: 200,
  },
  {
    name: 'Clotrimazole Cream',
    genericName: 'Clotrimazole',
    barcode: '8901234567934',
    brand: 'Mankind',
    category: 'Antifungal',
    unit: 'Pcs',
    price: 45.0,
    discountPct: 0,
    stock: 300,
  },
  {
    name: 'Mupirocin Ointment',
    genericName: 'Mupirocin',
    barcode: '8901234567935',
    brand: 'GlaxoSmithKline',
    category: 'Antibacterial',
    unit: 'Pcs',
    price: 120.0,
    discountPct: 0,
    stock: 150,
  },
  {
    name: 'Eye Drop Refresh',
    genericName: 'Carboxymethylcellulose',
    barcode: '8901234567936',
    brand: 'Allergan',
    category: 'Ophthalmic',
    unit: 'Pcs',
    price: 150.0,
    discountPct: 10,
    stock: 100,
  },
  {
    name: 'Nasal Drop',
    genericName: 'Oxymetazoline',
    barcode: '8901234567937',
    brand: 'Cipla',
    category: 'Nasal',
    unit: 'Pcs',
    price: 35.0,
    discountPct: 0,
    stock: 250,
  },
  {
    name: 'Gargle Mouthwash',
    genericName: 'Chlorhexidine Gluconate',
    barcode: '8901234567938',
    brand: 'Colgate',
    category: 'Oral',
    unit: 'Pcs',
    price: 95.0,
    discountPct: 0,
    stock: 180,
  },
  {
    name: 'Cough Syrup',
    genericName: 'Ambroxol + Levosalbutamol',
    barcode: '8901234567939',
    brand: 'Mankind',
    category: 'Respiratory',
    unit: 'Bottle',
    price: 85.0,
    discountPct: 8,
    stock: 300,
  },
  {
    name: 'Antacid Syrup',
    genericName: 'Magaldrate + Simethicone',
    barcode: '8901234567940',
    brand: 'Sun Pharma',
    category: 'Gastrointestinal',
    unit: 'Bottle',
    price: 65.0,
    discountPct: 0,
    stock: 350,
  },
];

async function seed() {
  await dataSource.initialize();
  console.log('Database connected');

  const repo = dataSource.getRepository(Medicine);

  for (const med of medicines) {
    const medicine = repo.create(med);
    await repo.save(medicine);
  }

  console.log(`Seeded ${medicines.length} medicines`);
  await dataSource.destroy();
}

seed().catch(console.error);
